services:
  - type: web
    name: yummy-kosher-grill-frontend
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./client/dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
